name: Conda

on:
  push:
    branches:
      - master
      - 'dev**'
  pull_request:
    paths:
      - 'tesseract**'
      - '.github/workflows/conda.yml'
      - '**.repos'
  release:
    types:
      - released

jobs:
  conda-win:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
      with:
       path: workspace/src/tesseract
    - name: install-depends
      shell: cmd
      run: |
        python -m pip install vcstool -q
    - name: vcs import
      run: >
        vcs import --input "${{ github.workspace }}/workspace/src/tesseract/.github/workflows/windows_dependencies.repos" workspace/src/
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channel-priority: true
        environment-file: ${{ github.workspace }}/workspace/src/tesseract/.github/workflows/conda/environment.yml
    - name: build and test
      run: |
        mamba activate test
        mkdir conda
        xcopy /E workspace\src\tesseract\.github\workflows\conda conda
        cd conda
        New-Item -Name conda-forge.yml -ItemType File
        conda smithy regenerate
        
        mamba mambabuild -m .ci_support/win_64_.yaml .

  conda-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: workspace/src/tesseract
    - name: install-depends
      run: |
        python -m pip install vcstool -q
    - name: vcs import
      run: >
        vcs import --input "${{ github.workspace }}/workspace/src/tesseract/.github/workflows/windows_dependencies.repos" workspace/src/
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channel-priority: true
        environment-file: ${{ github.workspace }}/workspace/src/tesseract/.github/workflows/conda/environment.yml
    - name: build and test
      run: |
        cp -r workspace/src/tesseract/.github/workflows/conda ./conda
        cd conda
        touch conda-forge.yml
        conda smithy regenerate
        
        mamba mambabuild -m .ci_support/linux_64_.yaml .
