name: Mac OSX

on:
  push:
    branches:
      - master
      - 'dev**'
  pull_request:
    paths:
      - 'tesseract**'
      - '.github/workflows/mac.yml'
      - '**.repos'
  schedule:
    - cron: '0 5 * * *'
  release:
    types:
      - released

env:
  VCPKG_PKGS: >- 
    boost-dll boost-program-options
    boost-serialization boost-filesystem
    tinyxml2 console-bridge assimp
    urdfdom octomap orocos-kdl pcl
    gtest benchmark flann jsoncpp
    yaml-cpp
    openblas lapack
    fcl ompl taskflow
    bullet3[multithreading,double-precision,rtti]
    ccd[double-precision] gperftools

jobs:
  build-macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
      with:
        path: ws/src/tesseract
    - uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: '3.12'
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v5
      with:
        pkgs: >-
          ${{ env.VCPKG_PKGS }}
        triplet: x64-osx-dynamic
        extra-args: --clean-after-build
        token: ${{ github.token }}
        cache-key: osx-x64-vcpkg
        revision: master
    - name: pip3
      run: |
        python3 -m pip install numpy setuptools wheel pytest delvewheel colcon-common-extensions vcstool
    - name: brew
      run: |
        brew install libomp cmake autotools autoconf
    - name: colcon build
      working-directory: ws
      run: |
        export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$GITHUB_WORKSPACE/vcpkg/installed/arm64-osx-dynamic/lib
        export CMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/vcpkg/installed/arm64-osx-dynamic

        colcon build --merge-install \
            --packages-ignore tesseract_examples trajopt_ifopt trajopt_sqp ifopt vhacd tesseract_python \
            --event-handlers console_cohesion+ \
            --cmake-force-configure \
            --cmake-args -GNinja -DCMAKE_BUILD_TYPE=Release \
            -DINSTALL_OMPL=OFF -DINSTALL_OMPL_TAG=master -DBUILD_IPOPT=OFF -DBUILD_SNOPT=OFF \
            -DBUILD_SHARED_LIBS=ON -DTESSERACT_ENABLE_EXAMPLES=OFF \
            -DVCPKG_APPLOCAL_DEPS=OFF -DTESSERACT_ENABLE_TESTING=ON
    - name: colcon test
      working-directory: ws
      run: |
        export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$GITHUB_WORKSPACE/vcpkg/installed/arm64-osx-dynamic/lib
        export CMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/vcpkg/installed/arm64-osx-dynamic

        colcon test --merge-install \
            --packages-ignore tesseract_examples trajopt_ifopt trajopt_sqp ifopt vhacd tesseract_python \
            --event-handlers console_cohesion+
    
