name: pre-commit

on:
  push:
    branches:
      - master
      - 'dev**'
  pull_request:
  schedule:
    - cron: '0 5 * * *'

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: apt
      run: |
        sudo apt update
        sudo apt install -y dos2unix
    - uses: pre-commit/action@v3.0.1
